import type { Metadata } from "next";

import "./globals.css";
import { geistMono, geistSans } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "LLM integiration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
    >
      <body className=" bg-white font-sans">{children}</body>
    </html>
  );
}
